import { StyleSheet } from "react-native";

export default mapStyles=StyleSheet.create({
    contanierMap:{
        width:'100%',
        height:'100%',
        backgroundColor:'#ffffff',
        display:'flex',
        justifyContent:'space-between',
        alignItems:'center'
    },
    textF:{
        color:'#000000'
    },
    container:{
        width:'100%',
        height:'100%',
        display:'flex',
        flexDirection:'column',
        justifyContent:'space-between',
        alignItems:'center'
    },
    mapContainer:{
        width:'100%',
        height:'80%',
        borderWidth:1,
        borderColor:'#000000'
    },
    testS:{
        height:'80%',
        width:'100%',
        display:'flex',
        justifyContent:'space-between',
        alignItems:'center',
        flexDirection:'column'
    },
    infoAndBtn:{
        display:'flex',
        width:'100%',
        flexDirection:'row',
        justifyContent:'center'
    },
    btnSeeMarks:{
        width:'40%',
        height:40,
        backgroundColor:'#000000',
        borderRadius:10,
        display:'flex',
        justifyContent:'center',
        alignItems:'center'
    },
    textMark:{
        color:'#ffffff'
    },
    choseVehiculeContianer:{
        width:'100%',
        height:'10%',

    },
    specialOptionsContainer:{
        width:'100%',
        height:'10%',
        borderColor:'#000000',
        borderWidth:2,
    },
    scrollLinesToChose:{
        width:'100%',
        height:'100%',
        backgroundColor:'#03AEE7'
    },
    boxLineOption:{
        width:50,
        height:50,
        borderColor:'#000000',
        borderWidth:2,
        marginLeft:20,
        borderRadius:5,
        display:'flex',
        justifyContent:'center',
        alignItems:'center',
    },
    textLineChosen:{
        fontSize:22,
        color:'#000000',
        fontWeight:'bold'
    }
})