import { StyleSheet } from "react-native";
export default stylesForListAviable = StyleSheet.create({
    container:{
        width:'100%',
        height:'100%',
        display:'flex',
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'#ffB400'
    },
    scrollContainer:{
        width:'95%',
        height:'90%',
        marginTop:10
    },
    boxBusOption:{
        width:'85%',
        height:100,
        borderWidth:2,
        borderColor:'#000000',
        marginBottom:15,
        borderRadius:10,
        display:'flex',
        justifyContent:'center',
        alignItems:'center'
    },
    textLineDescription:{
        fontSize:24,
    }
})